-- Create enquiries table in Supabase
CREATE TABLE IF NOT EXISTS public.enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  event_type TEXT,
  date TEXT,
  location TEXT,
  message TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.enquiries ENABLE ROW LEVEL SECURITY;

-- Allow anonymous users to submit enquiries
CREATE POLICY "Allow public insert to enquiries"
ON public.enquiries FOR INSERT
TO anon
WITH CHECK (true);

-- Allow authenticated users / service role to view enquiries
CREATE POLICY "Allow authenticated read enquiries"
ON public.enquiries FOR SELECT
TO authenticated
USING (true);
