-- Create enquiries table in Supabase
CREATE TABLE IF NOT EXISTS public.enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  event_type TEXT,
  date TEXT,
  location TEXT,
  message TEXT,
  ref_code TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.enquiries ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if re-running
DROP POLICY IF EXISTS "Allow public insert to enquiries" ON public.enquiries;
DROP POLICY IF EXISTS "Allow authenticated read enquiries" ON public.enquiries;

-- Allow anonymous users to INSERT enquiries
CREATE POLICY "Allow public insert to enquiries"
ON public.enquiries FOR INSERT
TO anon
WITH CHECK (true);

-- Allow authenticated users to SELECT all enquiries
CREATE POLICY "Allow authenticated read enquiries"
ON public.enquiries FOR SELECT
TO authenticated
USING (true);

-- =========================================================================
-- CREATE TICKET BOOKINGS TABLE FOR RAZORPAY SHOW TICKETING
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.ticket_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
  booking_ref TEXT NOT NULL UNIQUE,
  show_id TEXT NOT NULL,
  show_title TEXT NOT NULL,
  show_date TEXT NOT NULL,
  show_time TEXT,
  venue TEXT,
  city TEXT,
  tier_name TEXT NOT NULL,
  ticket_price NUMERIC NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  total_amount NUMERIC NOT NULL,
  buyer_name TEXT NOT NULL,
  buyer_email TEXT NOT NULL,
  buyer_phone TEXT NOT NULL,
  payment_id TEXT,
  payment_status TEXT DEFAULT 'PAID',
  check_in_status TEXT DEFAULT 'NOT_CHECKED_IN'
);

-- Enable Row Level Security (RLS) for ticket_bookings
ALTER TABLE public.ticket_bookings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert ticket bookings" ON public.ticket_bookings;
DROP POLICY IF EXISTS "Allow public and admin read ticket bookings" ON public.ticket_bookings;

-- Allow buyers to insert bookings after payment
CREATE POLICY "Allow public insert ticket bookings"
ON public.ticket_bookings FOR INSERT
TO anon
WITH CHECK (true);

-- Allow reading ticket bookings
CREATE POLICY "Allow public and admin read ticket bookings"
ON public.ticket_bookings FOR SELECT
TO anon, authenticated
USING (true);

-- Enable Realtime for ticket_bookings
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.ticket_bookings;
